[build-system]
requires = ["flit_core >=3.2,<4", "wheel"]
build-backend = "flit_core.buildapi"

[project]
name = "pyKook"
authors = [{name = "symlpigeon", email = "symlpigeon@foxmail.com"}]
readme = "README.md"
dynamic = ["version", "description"]
dependencies = [
"grequests", "websockets"
]
