[build-system]
requires = ["flit_core >=3.2,<4", "wheel", "grequests", "websockets"]
build-backend = "flit_core.buildapi"

[project]
name = "pyKook"
authors = [{name = "symlpigeon", email = "symlpigeon@foxmail.com"}]
readme = "README.md"
dynamic = ["version", "description"]
